on:
  push:
    tags:
      - 'v*'

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Checkout code
      uses: actions/checkout@master
    
    - run: yarn install

    - name: Set version and date in index.html
      run: |
        ref="${{ github.ref }}"
        tag="$(echo "${ref}" | awk -F/ '{print $NF}')"
        sed -i "s/__RELEASE_VERSION__/${tag}/g" index.html
        sed -i "s/__LAST_UPDATED__/$(date "+%Y-%m-%d")/g" index.html
        sed -i "s/__LAST_UPDATED_INSTANT__/$(date --iso-8601=seconds)/g" index.html

    - name: Build bundle
      run: yarn build

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: See commits for change list
        draft: false
        prerelease: false

    - name: Upload bundle to S3
      uses: jakejarvis/s3-sync-action@v0.5.0
      with:
        args: --delete --storage-class=REDUCED_REDUNDANCY
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_ORG }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_ORG }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_ORG }}
        AWS_REGION: eu-north-1 # Europe (Stockholm)
        SOURCE_DIR: dist
